apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-spring-batch
  namespace: spring-batch
  labels:
    app: basic-spring-batch
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-spring-batch
  template:
    metadata:
      labels:
        app: basic-spring-batch
        version: "1.0.0"
    spec:
      containers:
      - name: basic-spring-batch
        image: basic-spring-batch:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: spring-batch-config
              key: JAVA_OPTS
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        command: ["sh", "-c"]
        args: ["java $JAVA_OPTS -jar app.jar \"$@\"", "--"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux | grep java | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux | grep java | grep -v grep"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
